### ISSUE TITLE
tindicators

### ISSUE THREAD

**Issue by imsatoshi** [philipzabicki/binance-algotrading#1]
I tried to run code on Mac mini. Any idea to solve this?

OSError: dlopen(/Users/xxx/anaconda3/lib/python3.11/site-packages/tindicators/libindicators.dylib, 0x0006): tried: '/Users/xxx/anaconda3/lib/python3.11/site-packages/tindicators/libindicators.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/xxx/anaconda3/lib/python3.11/site-packages/tindicators/libindicators.dylib' (no such file), '/Users/xxx/anaconda3/lib/python3.11/site-packages/tindicators/libindicators.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

**Comment by philipzabicki** [comment]
It looks like a compatibility problem between the library and your CPU architecture. The library is compiled for a different architecture than what your Mac mini is using.

I'm not able to fix this issue for now, as I'm not the author of this library. You should report your issue to [tindicators](https://github.com/3jane/tindicators) as the author is able to fix this more quickly.

In the future, my repo will not use external libraries for TA indicators calculation, but for now, this is the fastest way as those are written in C.

**Comment by imsatoshi** [comment]
I will use other pc for testing. Thanks for reply!
